"""initial tables

Revision ID: 0001
Revises:
Create Date: 2026-09-28 14:19:54.599111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "check_ins",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mood", sa.SmallInteger(), nullable=False),
        sa.Column("energy", sa.SmallInteger(), nullable=False),
        sa.Column("focus", sa.SmallInteger(), nullable=False),
        sa.Column("note", sa.String(length=280), nullable=True),
        sa.CheckConstraint("energy BETWEEN 1 AND 5", name="ck_check_ins_energy_range"),
        sa.CheckConstraint("focus BETWEEN 1 AND 5", name="ck_check_ins_focus_range"),
        sa.CheckConstraint("mood BETWEEN 1 AND 5", name="ck_check_ins_mood_range"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_check_ins_user_id_created_at", "check_ins", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "data_source_settings",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "source_id"),
    )
    op.create_table(
        "usage_days",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("longest_focus_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "date"),
    )
    op.create_table(
        "app_usage",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("hour", sa.SmallInteger(), nullable=False),
        sa.Column("app_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("seconds", sa.Integer(), nullable=False),
        sa.Column("opens", sa.Integer(), nullable=False),
        sa.CheckConstraint("hour BETWEEN 0 AND 23", name="ck_app_usage_hour_range"),
        sa.ForeignKeyConstraint(
            ["user_id", "date"], ["usage_days.user_id", "usage_days.date"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "date", "hour", "app_id"),
    )
    op.create_table(
        "usage_hours",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("hour", sa.SmallInteger(), nullable=False),
        sa.Column("pickups", sa.Integer(), nullable=False),
        sa.Column("notifications", sa.Integer(), nullable=False),
        sa.CheckConstraint("hour BETWEEN 0 AND 23", name="ck_usage_hours_hour_range"),
        sa.ForeignKeyConstraint(
            ["user_id", "date"], ["usage_days.user_id", "usage_days.date"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "date", "hour"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage_hours")
    op.drop_table("app_usage")
    op.drop_table("usage_days")
    op.drop_table("data_source_settings")
    op.drop_index("ix_check_ins_user_id_created_at", table_name="check_ins")
    op.drop_table("check_ins")
    op.drop_table("users")
    # ### end Alembic commands ###
